--
-- File generated with SQLiteStudio v3.4.17 on Sun Sep 21 13:50:45 2025
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: questions
CREATE TABLE questions (id INTEGER PRIMARY KEY, question_text TEXT NOT NULL, question_type TEXT NOT NULL, explanation TEXT, reference TEXT, topic TEXT NOT NULL, subtopic TEXT NOT NULL);
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (1, 'Q1: Which of these is an example of a duplicate option error?', 'MCQ', 'Testing duplicate options', 'Test Ref', 'Test Topic', 'Duplicates');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (2, 'Q2: Which of these animals are mammals?', 'MCQ', 'Should be MCQ-Multiple but marked MCQ', 'Test Ref', 'Test Topic', 'Invalid Type');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (3, 'Q3: Select all prime numbers below.', 'MCQ-Multiple', 'Not all primes marked as correct', 'Test Ref', 'Test Topic', 'Missing Corrects');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (4, 'Q4: Which color is the sky usually during the day?', 'MCQ', 'All options are incorrect', 'Test Ref', 'Test Topic', 'No Correct');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (5, 'Q5: Match planets to their type.', 'Match', 'Left side duplicated', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (6, 'Q6: Match scientists to their discoveries.', 'Match', 'Right side duplicated', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (7, 'Q7: Assertion: The Earth is flat. Reason: Photos from space show curvature.', 'AssertionReason', 'No correct answer marked', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (8, 'Q7: Assertion: The Earth is flat. Reason: Photos from space show curvature.', 'AssertionReason', 'No correct answer marked', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (9, 'Q8: Duplicate option sample again', 'MCQ', 'Two identical options', 'Test Ref', 'Test Topic', 'Duplicates');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (10, 'Q9: Multiple correct mis-typed', 'MCQ', 'Should be MCQ-Multiple', 'Test Ref', 'Test Topic', 'Invalid Type');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (11, 'Q10: No correct MCQ', 'MCQ', 'Fails correctness', 'Test Ref', 'Test Topic', 'No Correct');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (12, 'Q11: Duplicate left in match', 'Match', 'Two left side entries are same', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (13, 'Q12: Duplicate right in match', 'Match', 'Two right side entries are same', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (14, 'Q13: Assertion: All birds can fly. Reason: They have wings.', 'AssertionReason', 'Two correct answers marked which is invalid', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (15, 'Q14: MCQ duplicate text conflicting correctness', 'MCQ', 'Same option text marked correct and incorrect', 'Test Ref', 'Test Topic', 'Duplicates');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (16, 'Q15: All options marked correct', 'MCQ-Multiple', 'All answers marked correct makes it useless', 'Test Ref', 'Test Topic', 'Marking Error');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (17, 'Q16: Assertion: Sun rises in west. Reason: Earth rotates east to west.', 'AssertionReason', 'No options attached makes it invalid', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (18, 'Q17: Match duplicate left and right both', 'Match', 'Both left_text and right_text have dupes', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (19, 'Q18: MCQ-Multiple with only one correct', 'MCQ-Multiple', 'Should have multiple corrects but only one set', 'Test Ref', 'Test Topic', 'Inconsistent Marking');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (20, 'Q19: Invalid question type test', 'XYZ', 'Question type not allowed', 'Test Ref', 'Test Topic', 'Type Error');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (21, 'Q20: MCQ with no correct answers again', 'MCQ', 'Fails correctness rule', 'Test Ref', 'Test Topic', 'No Correct');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (22, 'Q21: MCQ duplicate options again', 'MCQ', 'Two identical options appear', 'Test Ref', 'Test Topic', 'Duplicates');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (23, 'Q22: MCQ wrongly typed with multiple correct answers', 'MCQ', 'Should be MCQ-Multiple', 'Test Ref', 'Test Topic', 'Invalid Type');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (24, 'Q23: MCQ-Multiple primes but only some correct marked', 'MCQ-Multiple', 'Partial correctness set', 'Test Ref', 'Test Topic', 'Missing Corrects');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (25, 'Q24: MCQ all wrong', 'MCQ', 'None of the options is correct', 'Test Ref', 'Test Topic', 'No Correct');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (26, 'Q25: Match duplicate left test', 'Match', 'Same left twice', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (27, 'Q26: Match duplicate right test', 'Match', 'Same right twice', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (28, 'Q27: Assertion: Fish can walk. Reason: They have legs.', 'AssertionReason', 'All options wrong', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (29, 'Q28: Assertion: Fire is cold. Reason: It emits heat.', 'AssertionReason', 'Two correct marked', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (30, 'Q29: Invalid type entry', 'ABC', 'Wrong type string', 'Test Ref', 'Test Topic', 'Type Error');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (31, 'Q30: MCQ-Multiple anomaly with only one correct', 'MCQ-Multiple', 'Should have multiple corrects', 'Test Ref', 'Test Topic', 'Inconsistent Marking');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (32, 'Q31: MCQ duplicate options', 'MCQ', 'Two identical options', 'Test Ref', 'Test Topic', 'Duplicates');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (33, 'Q32: MCQ with multiple correct but wrong type', 'MCQ', 'Should be MCQ-Multiple', 'Test Ref', 'Test Topic', 'Invalid Type');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (34, 'Q33: MCQ-Multiple partial marking', 'MCQ-Multiple', 'Not all marked', 'Test Ref', 'Test Topic', 'Missing Corrects');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (35, 'Q34: MCQ no correct again', 'MCQ', 'All options wrong', 'Test Ref', 'Test Topic', 'No Correct');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (36, 'Q35: Match duplicate left', 'Match', 'Left dupes', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (37, 'Q36: Match duplicate right', 'Match', 'Right dupes', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (38, 'Q37: AR with all wrong', 'AssertionReason', 'None correct', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (39, 'Q38: AR with multiple correct', 'AssertionReason', 'Invalid multiple', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (40, 'Q39: Invalid type example', 'FOO', 'Bad type', 'Test Ref', 'Test Topic', 'Type Error');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (41, 'Q40: MCQ-Multiple but only one correct', 'MCQ-Multiple', 'Only one marked correct', 'Test Ref', 'Test Topic', 'Inconsistent Marking');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (42, 'Q41: MCQ duplicate sample', 'MCQ', 'Duplicate option text', 'Test Ref', 'Test Topic', 'Duplicates');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (43, 'Q42: Wrongly typed MCQ with multi correct', 'MCQ', 'Should be MCQ-Multiple', 'Test Ref', 'Test Topic', 'Invalid Type');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (44, 'Q43: MCQ-Multiple incomplete marking', 'MCQ-Multiple', 'Missing some correct answers', 'Test Ref', 'Test Topic', 'Missing Corrects');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (45, 'Q44: MCQ no correct test', 'MCQ', 'Fails correctness', 'Test Ref', 'Test Topic', 'No Correct');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (46, 'Q45: Match dupe left again', 'Match', 'Invalid duplication', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (47, 'Q46: Match dupe right again', 'Match', 'Invalid duplication', 'Test Ref', 'Test Topic', 'Match Dupes');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (48, 'Q47: AR with all options wrong', 'AssertionReason', 'Zero correct answer', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (49, 'Q48: AR invalid multiple correct', 'AssertionReason', 'Two marked correct', 'Test Ref', 'Test Topic', 'AR Invalid');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (50, 'Q49: Invalid type case', '123', 'Wrong type value', 'Test Ref', 'Test Topic', 'Type Error');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (51, 'Q50: MCQ-Multiple anomaly again', 'MCQ-Multiple', 'Only one correct marked', 'Test Ref', 'Test Topic', 'Inconsistent Marking');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (52, 'Q51: Match with no pairs provided', 'Match', 'A Match question that has no match_pairs', 'Test Ref', 'Test Topic', 'Match Missing');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (53, 'V1: What does OE mean according to Porter?', 'MCQ', 'OE means performing activities better than rivals', 'Porter', 'Strategy', 'OE');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (54, 'V2: Which are sources of strategic positioning?', 'MCQ-Multiple', 'Variety, Needs, Access are the three sources', 'Porter', 'Strategy', 'Positioning');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (55, 'V3: Match thinkers with contributions', 'Match', 'Sun Tzu, Clausewitz, Lawrence linked to strategy origins', 'Lecture', 'Strategy', 'Origins');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (56, 'V4: Assertion (A): Trade-offs protect strategy. Reason (R): They force clear choices.', 'AssertionReason', 'Both A and R true, R explains A', 'Porter', 'Strategy', 'Trade-offs');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (57, 'V5: Which airline exemplifies low-cost fit?', 'MCQ', 'Southwest aligns activities to deliver low-cost model', 'Porter', 'Strategy', 'Case');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (58, 'V6: What is the essence of strategy?', 'MCQ', 'It is about making choices, including what not to do', 'Porter', 'Strategy', 'Essence');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (59, 'V7: Why do trade-offs arise?', 'MCQ-Multiple', 'Due to image inconsistencies, activity conflicts, coordination limits', 'Porter', 'Strategy', 'Trade-offs');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (60, 'V8: Match company with positioning', 'Match', 'Ikea, Neutrogena, Vanguard matched with their strategies', 'Lecture', 'Strategy', 'Cases');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (61, 'V9: What is competitive convergence?', 'MCQ', 'When rivals imitate each other, firms converge and lose uniqueness', 'Porter', 'Strategy', 'OE Limits');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (62, 'V10: Assertion (A): Strategy is about alignment. Reason (R): Activities must reinforce each other.', 'AssertionReason', 'Both A and R are true and R explains A', 'Porter', 'Strategy', 'Fit');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (63, 'V11: Which is Ikea''s trade-off?', 'MCQ', 'Ikea says no to full service in exchange for self-service and low cost', 'Porter', 'Strategy', 'Case');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (64, 'V12: Which line item best shows competitive advantage?', 'MCQ', 'Operating profit reflects true advantage, not net profit', 'Lecture', 'Strategy', 'Metrics');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (65, 'V13: Match type of positioning with example', 'Match', 'Variety, Needs, Access matched with examples', 'Lecture', 'Strategy', 'Positioning');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (66, 'V14: Assertion (A): OE is not strategy. Reason (R): OE improvements can be copied quickly.', 'AssertionReason', 'Both A and R are true and R explains A', 'Porter', 'Strategy', 'OE vs Strategy');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (67, 'V15: Which company pursued index funds for low cost?', 'MCQ', 'Vanguard focused on low cost index funds with steady returns', 'Porter', 'Strategy', 'Case');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (68, 'V16: Which are levels of fit?', 'MCQ-Multiple', 'First order consistency, second order reinforcement, third order optimization', 'Porter', 'Strategy', 'Fit');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (69, 'V17: Match concept with example', 'Match', 'Productivity frontier, Growth trap, Straddling examples', 'Lecture', 'Strategy', 'Applications');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (70, 'V18: Which metric shows true long-term advantage?', 'MCQ', 'Operating profit is best indicator of sustained advantage', 'Lecture', 'Strategy', 'Metrics');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (71, 'V19: Which bank focused only on UHNW clients?', 'MCQ', 'Bessemer Trust served only $5M+ families with customized services', 'Lecture', 'Strategy', 'Case');
INSERT INTO questions (id, question_text, question_type, explanation, reference, topic, subtopic) VALUES (72, 'V20: Assertion (A): Growth can dilute strategy. Reason (R): It often leads to straddling and weak fit.', 'AssertionReason', 'Both A and R are true and R explains A', 'Lecture', 'Strategy', 'Growth vs Strategy');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
